

- name: create ccnet-conf
  template: 
    src: ccnet.conf.j2
    dest: "{{ seafile_configuration_path }}/ccnet.conf"


- name: create seafile-conf
  template: 
    src: seafile.conf.j2
    dest: "{{ seafile_configuration_path }}/seafile.conf"    


- name: create seafile ini
  template: 
    src: seafile.ini.j2
    dest: "{{ seafile_configuration_path }}/seafile.ini"    


- name: create seahub settings
  template: 
    src: seahub_settings.py.j2
    dest: "{{ seafile_configuration_path }}/seahub_settings.py"   
  notify:
  - restart seafile
   
   
- name: link key and ini to ccnet directory
  file:
    src: "{{ seafile_configuration_path }}/{{ item }}"
    path: "{{ seafile_configuration_path_ccnet }}/{{ item }}"
    state: link
  with_items:
  - mykey.peer
  - seafile.ini

# helper scripts

- name: user creation bash script
  template:
    src: create_user.sh
    dest: "{{ seafile_installation_path }}/create_user.sh"
    mode: 0755
    
    
- name: user creation python script
  template:
    src: create_user.py
    dest: "{{ seafile_installation_path }}/create_user.py"
    mode: 0644
  
  
- name: admin creation bash script
  template:
    src: init_admin.sh
    dest: "{{ seafile_installation_path }}/init_admin.sh"
    mode: 0755
  register: _seafile_admin_bootstrap
  
  
- name: admin creation python script
  template:
    src: init_admin.py
    dest: "{{ seafile_installation_path }}/init_admin.py"
    mode: 0644


- name: create seafile users
  command: "{{ seafile_installation_path }}/create_user.sh {{ item }} {{ lookup('password', seafile_local_storage_path + '/' + item + ' length=18') }}"
  with_items: "{{ seafile_create_users }}"
  tags:
  - seafile-users
  
  
